In [16]:
import torch

In [17]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x.shape

torch.Size([12])

In [19]:
y = x.reshape(3,4)
# reshape 是返回一个地址指针，不会创建新的空间
y[:] = 2
y

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [20]:
x = torch.arange(6)
y = torch.zeros(6)

z = x ** y
z,x

(tensor([1., 1., 1., 1., 1., 1.]), tensor([0, 1, 2, 3, 4, 5]))

In [21]:
y = torch.randn(10000).reshape(100, 100)
x = torch.ones(10000).reshape(100, 100)

# 原地执行，确保不会销毁分配新内存，造成巨量性能浪费
z = torch.zeros_like(y)
before=id(z)
z[:] = y + x
id(z)==before

True

In [22]:
# 销毁分配新内存
z = torch.zeros_like(y)
before=id(z)
z = y + x
id(z)==before

False

In [23]:
before2 = id(y)
y[:]=y+x
id(y)==before2

# 也可使用 x+=y,x[:]=x+y减少内存开销

True

In [24]:
a = x.numpy()
b = torch.tensor(a)
type(a),type(b)

(numpy.ndarray, torch.Tensor)

In [25]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [26]:
c = a + b
c

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [27]:
import torch
a = torch.randn(1,dtype=torch.float32)
a,a.item(), int(a)

(tensor([-0.4331]), -0.43307438492774963, 0)

In [28]:
b = torch.randn(6)
b

tensor([-0.6751, -0.3726, -0.2296,  0.9390, -2.2941, -1.0133])