In [25]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [ ]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [ ]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [26]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [27]:
# 需要处理的作为input， 无需处理的列直接output

inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
#平均值填充
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [28]:
outputs

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

In [29]:
# 将类别值按01转换成离散数值，每种类别值Pave，NaN变成一个新列 
# dummies仿制品
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [30]:
# 将pandas类型转化为torch张量
import torch
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)

X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [34]:
y.reshape(4,1)

tensor([[127500],
        [106000],
        [178100],
        [140000]])

In [3]:
import torch

# 示例数据
tensor1 = torch.tensor([[3., 1., 0.],
                        [2., 0., 1.],
                        [4., 0., 1.],
                        [3., 0., 1.]], dtype=torch.float32)

tensor2 = torch.tensor([[127500],
                        [106000],
                        [178100],
                        [140000]])

# 在第二维上合并
combined_tensor = torch.cat((tensor1, tensor2), dim=1)
# 设置全局打印选项以保留两位小数,不使用科学计数法
torch.set_printoptions(precision=2,sci_mode=False)
combined_tensor,tensor2.shape

(tensor([[      3.,       1.,       0.,  127500.],
         [      2.,       0.,       1.,  106000.],
         [      4.,       0.,       1.,  178100.],
         [      3.,       0.,       1.,  140000.]]),
 torch.Size([4, 1]))