In [2]:
import torch

x = torch.arange(4)
y = x.T
x,y

C:\Users\Raisei\AppData\Local\Temp\ipykernel_14072\28145594.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3575.)
  y = x.T


(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [3]:
a = 2
x = torch.arange(24,dtype=torch.float32).reshape(2,3,4)
x

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [4]:
x,x+a,x*a
# 当使用a=2,x+=a, 实际上是加4，因为a为64，x为32.
# 而x+a不会有这个问题

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.]],
 
         [[14., 15., 16., 17.],
          [18., 19., 20., 21.],
          [22., 23., 24., 25.]]]),
 tensor([[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.]],
 
         [[24., 26., 28., 30.],
          [32., 34., 36., 38.],
          [40., 42., 44., 46.]]]))

In [5]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [6]:
x.sum(),x.shape

(tensor(276.), torch.Size([2, 3, 4]))

In [7]:
# 只对前两个维度求和
x.sum(axis=[0,1])

tensor([60., 66., 72., 78.])

In [8]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [9]:
# 按维度求和，并保留指定维度
sum_A = A.sum(axis=1,keepdim=True)
A.shape,sum_A,sum_A.shape

(torch.Size([5, 4]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [10]:
# 求占比，归一化广播
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A / sum_A,A

(tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [11]:
# 完全保留维度求和，渐进式求和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [12]:
# 向量点积
x=torch.arange(4,dtype=torch.float32)
y=x+1
x,y,torch.dot(x,y),torch.sum(x*y)==torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 2., 3., 4.]), tensor(20.), tensor(True))

In [13]:
# 矩阵向量积
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [14]:
# L2范数是平方和开根，L1是绝对值的和
A.norm(),A.abs().sum()

(tensor(49.6991), tensor(190.))

In [15]:
import torch
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [16]:
a.sum(axis=[0]).shape

torch.Size([5, 4])

In [25]:
b=a.sum(axis=[0,2])
b,b.shape

(tensor([8., 8., 8., 8., 8.]), torch.Size([5]))

In [24]:
b = a.sum(axis=[0,2],keepdim=True)
b,b.shape

(tensor([[[8.],
          [8.],
          [8.],
          [8.],
          [8.]]]),
 torch.Size([1, 5, 1]))

In [33]:
import torch
A = torch.arange(24).reshape(6,4)
B = A.sum(axis=1)

len(A),len(B),A,B

(6,
 6,
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]),
 tensor([ 6, 22, 38, 54, 70, 86]))

In [35]:
# 因为维度不同会出错
B = A.sum(axis=0)
A / B

tensor([[0.0000, 0.0152, 0.0278, 0.0385],
        [0.0667, 0.0758, 0.0833, 0.0897],
        [0.1333, 0.1364, 0.1389, 0.1410],
        [0.2000, 0.1970, 0.1944, 0.1923],
        [0.2667, 0.2576, 0.2500, 0.2436],
        [0.3333, 0.3182, 0.3056, 0.2949]])

In [36]:
C = A.sum(axis=1).reshape(6,1)
A / C

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714],
        [0.2326, 0.2442, 0.2558, 0.2674]])

In [23]:
# L2范数
A = torch.arange(24,dtype=torch.float32).reshape(2,3,4)
torch.linalg.norm(A)

tensor(65.7571)

In [29]:
# 求L1范数
torch.linalg.norm(A,ord=1,dim=[0,1])

tensor([28., 30., 32., 34.])