In [36]:
import torch

x = torch.arange(4)
y = x.T
x,y

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [37]:
a = 2
x = torch.arange(24,dtype=torch.float32).reshape(2,3,4)
x

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [38]:
x,x+a,x*a
# 当使用a=2,x+=a, 实际上是加4，因为a为64，x为32.
# 而x+a不会有这个问题

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 tensor([[[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.]],
 
         [[14., 15., 16., 17.],
          [18., 19., 20., 21.],
          [22., 23., 24., 25.]]]),
 tensor([[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.]],
 
         [[24., 26., 28., 30.],
          [32., 34., 36., 38.],
          [40., 42., 44., 46.]]]))

In [39]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [40]:
x.sum(),x.shape

(tensor(276.), torch.Size([2, 3, 4]))

In [41]:
# 只对前两个维度求和
x.sum(axis=[0,1])

tensor([60., 66., 72., 78.])

In [48]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [52]:
# 按维度求和，并保留指定维度
sum_A = A.sum(axis=1,keepdim=True)
A.shape,sum_A,sum_A.shape

(torch.Size([5, 4]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [43]:
# 求占比
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [46]:
# 完全保留维度求和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [44]:
# 向量点积
x=torch.arange(4,dtype=torch.float32)
y=x+1
x,y,torch.dot(x,y),torch.sum(x*y)==torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 2., 3., 4.]), tensor(20.), tensor(True))

In [45]:
# 矩阵向量积
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [50]:
# L2范数是平方和开根，L1是绝对值的和
A.norm(),A.abs().sum()

(tensor(49.6991), tensor(190.))