In [105]:
import numpy as np
import pandas as pd

In [106]:
print("列表创建一维数组")
data = [1,2,3,4,5]
x = np.array(data)
print(x)
print(x.dtype)

列表创建一维数组
[1 2 3 4 5]
int32


In [107]:
print("元组创建二维数组")
data2=([1,2],[2,3],[5,6])
x= np.array(data2)
print(x)
print(x.ndim) #维度
print(x.shape) #各维度大小

元组创建二维数组
[[1 2]
 [2 3]
 [5 6]]
2
(3, 2)


In [108]:
print("创建zero,ones,empyt")

print("zeros一维")
arr1 = np.zeros(4)
print(arr1)

print("zeros二维")
arr2=np.zeros((3,2))
print(arr2)

print("ones")
arr3=np.ones((2,2))
print(arr3)

print("空二维数组")
arr4=np.empty((2,3))
print(arr4)

print("等差数列")
print(np.arange(5))
print(np.arange(0,10,2))

创建zero,ones,empyt
zeros一维
[0. 0. 0. 0.]
zeros二维
[[0. 0.]
 [0. 0.]
 [0. 0.]]
ones
[[1. 1.]
 [1. 1.]]
空二维数组
[[0. 0. 0.]
 [0. 0. 0.]]
等差数列
[0 1 2 3 4]
[0 2 4 6 8]


In [109]:
# In[5]:
print("数组与标量，数组与数组的运算:")
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5 * 3)

arr6 = np.array([[1,4,9],[16,25,32]])
print(arr5*2+arr6)

数组与标量，数组与数组的运算:
[[ 3  6  9]
 [12 15 18]]
[[ 3  8 15]
 [24 35 44]]


In [110]:
print("数组的基本索引")
arr7=np.array([[1,2],[3,4],[5,6]])

print(arr7[0])
print(arr7[1][1])
print(arr7[0,1])

#三维数组
arr7=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
y = arr7[0].copy()
print(y)
print(y[0,0])

y[0][0]=0
print(y)

数组的基本索引
[1 2]
4
2
[[1 2]
 [3 4]]
1
[[0 2]
 [3 4]]


In [111]:
print("ndarray切片的一维应用")
arr9=np.array([1,2,3,4,5,6,7,8,9])
print(arr9[1:4])
print(arr9[:2])
print(arr9[2:])
print(arr9[0:5:2])

print("二维切片")
arr10 = np.array([[1,2],[3,4],[5,6]])
print(arr10[:2])
print(arr10[0:3:2])


ndarray切片的一维应用
[2 3 4]
[1 2]
[3 4 5 6 7 8 9]
[1 3 5]
二维切片
[[1 2]
 [3 4]]
[[1 2]
 [5 6]]


In [112]:
print("T属性")
arr11=np.arange(9)
arr12=arr11.reshape((3,3)) #维度变换
print(arr11)
print(arr12)

print("转置")
print(arr12.T)
print(np.dot(arr12,arr12.T)) #点乘法 横列乘数列


T属性
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
转置
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]


In [113]:
arr11=np.arange(8).reshape((2,2,2))

print("tanspose方法")
#轴变换
arr12 = arr11.transpose((1,0,2)) # arr12[x][y][z] = arr11[y][x][z]
print(arr12)

print("swapaxes")
#xy轴互换
arr12 = arr11.swapaxes(1,0)
print(arr12)
print(arr12[0][1][0])

arr12 = np.arange(9).reshape((3,3))
print(arr12)
print(arr12.swapaxes(1,0))


tanspose方法
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
swapaxes
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
4
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [114]:
print("一元ufunc示例")
arr13 = np.arange(6)
print(arr13)

print(np.square(arr13))
arr14=np.array([1.5,1.6,1.7,1.8])
y,z=np.modf(arr14)
print(y)
print(z)


一元ufunc示例
[0 1 2 3 4 5]
[ 0  1  4  9 16 25]
[0.5 0.6 0.7 0.8]
[1. 1. 1. 1.]


In [115]:
arr15 = np.array([[1,2],[3,4]])
arr16 = np.array([[5,6],[7,8]])


print(np.maximum(arr15,arr16))
print(np.minimum(arr15,arr16))

[[5 6]
 [7 8]]
[[1 2]
 [3 4]]


Pandas的使用：Series和DataFrame

In [116]:
obj = pd.Series([2,445,-41,57])
print(obj)
obj.values
obj.index

0      2
1    445
2    -41
3     57
dtype: int64


RangeIndex(start=0, stop=4, step=1)

In [117]:
obj2 = pd.Series([321,65467,12],index=['a','b','c'])
obj2
obj2[['a','c']]
nums = {'trick':2,'fuck':3,'more':'3vd'}
obj3 = pd.Series(nums)
obj3

trick      2
fuck       3
more     3vd
dtype: object

In [119]:
data = { "name":["angel","tom","anna"],
    "age":[52,65,23],
    "score":[89,76,98] }

frame = pd.DataFrame(data)
frame
frame1 = pd.DataFrame(data,columns=["name","score"])
frame1

name  score
0  angel     89
1    tom     76
2   anna     98

In [127]:
frame2 = pd.DataFrame(data,columns=["name","age","score","city"],index=["one","two","three"])
frame2
frame2["name"]
frame2.loc["two"]
frame2["city"]="Xi an"
frame2

frame2["one"]=["Leon",21,"beijing"]
frame2

name  age  score   city      one
one    angel   52     89  Xi an     Leon
two      tom   65     76  Xi an       21
three   anna   23     98  Xi an  beijing

In [130]:
frame3 = pd.DataFrame(np.arange(15).reshape(5,3),index=["one","two","three","four","five"],columns=["first","second","third"])
frame3
frame3["first"]["one"] = 50
frame3

first  second  third
one       50       1      2
two        3       4      5
three      6       7      8
four       9      10     11
five      12      13     14